Add option to use RG tags from fastq file

diff --git a/bin/speedseq b/bin/speedseq
--- a/bin/speedseq
+++ b/bin/speedseq
@@ -155,6 +155,7 @@ positional args:
 alignment options:
          -o STR   output prefix [in1.fq]
          -R       read group header line such as \"@RG\tID:id\tSM:samplename\tLB:lib\" (required)
+         -C       ignore the -R argument and assume fastq header contains RG information
          -p       first fastq file consists of interleaved paired-end sequences
          -t INT   threads [1]
          -T DIR   temp directory [./output_prefix.XXXXXXXXXXXX]
@@ -211,6 +212,9 @@ global options:
 		RG="$OPTARG"
 		RG_FMT="-R '$OPTARG'"
 		;;
+        C)
+        IGNORE_RG=1
+        ;;
 	    p)
 		INTERLEAVED=1
 		;;
@@ -296,11 +300,17 @@ global options:
     OUTBASE=`basename "$OUTPUT"`
 
     # Check for readgroup flag
-    if [[ -z $RG_FMT ]]
+    if [[ $IGNORE_RG == 1 ]]
     then
-	align_usage
-	echo -e "Error: no readgroup found. Please set a readgroup with the -R flag.\n"
-	exit 1
+        RG_FMT=""
+        #Assume fastq contains RG tag
+    else 
+        if [[ -z $RG ]]
+        then
+	    align_usage
+	    echo -e "Error: no readgroup found. Please set a readgroup with the -R flag.\n"
+	    exit 1
+        fi
     fi
 
     # Check that SORT_MEM > 2
